name: kagayaku
description: Free and open source novel reader for Android and iOS.
publish_to: 'none'
repository: https://github.com/Zerolmntrix/kagayaku
version: 1.1.0-dev

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #ui
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  pull_to_refresh: ^2.0.0

  # core
  go_router: ^10.0.0
  html: ^0.15.4
  http: ^1.1.0
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
