name: kagayaku
description: Free and open source novel reader for Android and iOS.
publish_to: 'none'
repository: https://github.com/Zerolmntrix/kagayaku
version: 1.2.2-dev

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  kagayaku_modules:
    git:
      url: https://github.com/Zerolmntrix/kagayaku-modules.git
      ref: dev

  #ui
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  pull_to_refresh: ^2.0.0
  percent_indicator: ^4.2.3
  modal_bottom_sheet: ^2.1.2

  # core
  go_router: ^11.1.2
  html: ^0.15.4
  dio: ^5.3.3
  connectivity_plus: ^4.0.2
  flutter_riverpod: ^2.4.3
  flutter_inappwebview: 6.0.0-beta.24+1

  # data management
  sqflite: ^2.3.0
  flutter_cache_manager: ^3.3.1
  path_provider: ^2.1.1
  path: ^1.8.3

  #utils
  share_plus: ^7.1.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
